Authentication implemented with bcrypt
xleed-dev/Rails-Blog pull request #1
Opened 2021-02-10 14:04 UTC by xleed-dev

- Added bcrypt package for a basic authentication system
- Added routes, models, and controllers for `Session` and `User`
- Login LogOut and SignUp implemented and working
- Created a *Wellcome* page with links to Login and SignUp for unregistered/unlogged users
- `User` views implemented: `index` and `show` (for the forthcoming *followers* functionality)

2021-02-10 22:13 UTC, juanhurtado10 requested changes
@xleed-dev outstanding PR some comments were added 🚀

2021-02-10 22:13 UTC, juanhurtado10 commented on Gemfile
> +gem 'bcrypt'
@xleed-dev what bcrypt does?

2021-02-10 22:13 UTC, juanhurtado10 commented on app/controllers/application_controller.rb
> +        User.find_by(id: session[:user_id])
@xleed-dev indentation is important you can configure the text editor you are using to automatically handle this for you. 1 tab (2 spaces)

2021-02-10 22:13 UTC, juanhurtado10 commented on app/controllers/application_controller.rb
> +end
@xleed-dev as a good coding practice tip all the files should end within a blank line

2021-02-10 22:13 UTC, juanhurtado10 commented on app/controllers/categories_controller.rb
>          @categories = Category.all
@xleed-dev indentation needed

2021-02-10 22:13 UTC, juanhurtado10 commented on app/controllers/application_controller.rb
> +    before_action :authorized
@xleed-dev why before_action is useful?

2021-02-10 22:13 UTC, juanhurtado10 commented on app/controllers/application_controller.rb
> +    helper_method :logged_in?
@xleed-dev what a helper_method does?

2021-02-10 22:13 UTC, juanhurtado10 commented on app/controllers/application_controller.rb
> +        unless defined? @categories
@xleed-dev how **defined?** works?

2021-02-10 22:13 UTC, juanhurtado10 commented on app/controllers/application_controller.rb
> +        redirect_to '/unauthorized' unless logged_in?
@xleed-dev a better approach is to use the Rail routing helper methods. This will prevent you to update all the code instances if for some reason a route changes. Please correct!

2021-02-10 22:13 UTC, juanhurtado10 commented on app/controllers/application_controller.rb
> +            @categories = Category.all.map { |c| c.name }
@xleed-dev what the method **.map** does?

2021-02-10 22:13 UTC, juanhurtado10 commented on app/controllers/application_controller.rb
> +            @categories = Category.all.map { |c| c.name }
@xleed-dev what the method **.map** does?

2021-02-10 22:13 UTC, juanhurtado10 commented on app/controllers/sessions_controller.rb
> +  skip_before_action :authorized, only: [:new, :create, :wellcome, :auth_errors, :unauthorized]
@xleed-dev I like to see ** skip_before_action** why is it useful?

2021-02-10 22:13 UTC, juanhurtado10 commented on app/controllers/sessions_controller.rb
> +      redirect_to '/articles'
@xleed-dev same here we need to change this by the routing helper methods

2021-02-10 22:13 UTC, juanhurtado10 commented on app/controllers/users_controller.rb
> +    @user = User.create(params.require(:user).permit(:username,:password))
@xleed-dev what if this line for some reason fails?

2021-02-10 22:13 UTC, juanhurtado10 commented on app/views/layouts/application.html.erb
> +              <%= link_to 'Logout', "/logout", method: "delete", class: "dropdown-item" %>
@xleed-dev why the **method: ** attribute is needed here?

2021-02-10 22:13 UTC, juanhurtado10 commented on app/views/layouts/external.html.erb
> +                                <% cached_categories.sample(15).each do |category| %>
@xleed-dev could you please explain what the **cached_categories** method does?

2021-02-11 14:54 UTC, xleed-dev commented on Gemfile
> +gem 'bcrypt'
This package provides various methods to store and validate passwords through a hashing algorithm so I can authenticate users directly in the controllers

2021-02-11 14:56 UTC, xleed-dev commented on app/controllers/application_controller.rb
> +        User.find_by(id: session[:user_id])
Got it, thanks for the recommendation 🖖

2021-02-11 15:06 UTC, xleed-dev commented on app/controllers/application_controller.rb
> +    before_action :authorized
It guarantees that when any controller action is fired this top-level controller calls the `authorized` method first before proceeding, the `authorized` method  validates if there is a valid user currently logged in, if not, the request is rejected

2021-02-11 15:09 UTC, xleed-dev commented on app/controllers/application_controller.rb
> +    helper_method :logged_in?
It exposes an instance method to its views so it can be accessed from `erb` files. In this case, the helper methods are declared in the *root* Controller so they can be accessed from other controllers and views

2021-02-11 15:22 UTC, xleed-dev commented on app/controllers/application_controller.rb
> +        unless defined? @categories
It returns the type of the argument as a string or `nil` if the passed argument doesn't exist. As I learned in the udemy course, the only *falsy* values are `nil` and `false` so I use `defined?` to check if I already fetched the categories from DB

2021-02-11 15:23 UTC, xleed-dev commented on app/controllers/application_controller.rb
> +        redirect_to '/unauthorized' unless logged_in?
Got it, thanks for the recommendation 🖖🏻

2021-02-11 15:32 UTC, xleed-dev commented on app/controllers/application_controller.rb
> +            @categories = Category.all.map { |c| c.name }
It allows me to create an array iterating over all the categories taking from each one only the data I need, in this case, its name

2021-02-11 15:35 UTC, xleed-dev commented on app/controllers/application_controller.rb
> +            @categories = Category.all.map { |c| c.name }
Returns an array in which each entry is assigned to the return of the block attached to the method

2021-02-11 15:45 UTC, xleed-dev commented on app/controllers/sessions_controller.rb
> +  skip_before_action :authorized, only: [:new, :create, :wellcome, :auth_errors, :unauthorized]
It allows omitting the "*current user is logged in*" check defined in the ApplicationController class for specific views, in this case, I want any unregistered user to be able to visit the pages that allow to sign up, login and see errors

2021-02-11 15:45 UTC, xleed-dev commented on app/controllers/sessions_controller.rb
> +      redirect_to '/articles'
Got it 🖖🏻

2021-02-11 15:53 UTC, xleed-dev commented on app/controllers/users_controller.rb
> +    @user = User.create(params.require(:user).permit(:username,:password))
In this case, as the user is not authenticated he is redirected to the *Wellcome* view. I have to implement the necessary logic to show errors directly in the login view

2021-02-11 15:56 UTC, xleed-dev commented on app/views/layouts/application.html.erb
> +              <%= link_to 'Logout', "/logout", method: "delete", class: "dropdown-item" %>
I see it as a convention because with the logout action we are *deleting* the current session. Should I omit it?

2021-02-11 16:00 UTC, xleed-dev commented on app/views/layouts/external.html.erb
> +                                <% cached_categories.sample(15).each do |category| %>
I created it as an optimization attempt because I noticed in the `rails server` console that the SQL query was getting performed twice when the welcome view was rendered

2021-02-12 15:29 UTC, juanhurtado10 commented on Gemfile
> +gem 'bcrypt'
Awesome! 👏🏻

2021-02-12 15:30 UTC, juanhurtado10 commented on app/controllers/application_controller.rb
> +    helper_method :logged_in?
@xleed-dev excellent!

2021-02-12 15:30 UTC, juanhurtado10 commented on app/controllers/application_controller.rb
> +        unless defined? @categories
@xleed-dev It's correct!

2021-02-12 15:31 UTC, juanhurtado10 commented on app/controllers/application_controller.rb
> +            @categories = Category.all.map { |c| c.name }
@xleed-dev ✅

2021-02-12 15:32 UTC, juanhurtado10 commented on app/controllers/users_controller.rb
> +    @user = User.create(params.require(:user).permit(:username,:password))
@xleed-dev please, go ahead! Thank you!

2021-02-12 15:33 UTC, juanhurtado10 commented on app/views/layouts/application.html.erb
> +              <%= link_to 'Logout', "/logout", method: "delete", class: "dropdown-item" %>
@xleed-dev nope, it depends on the route action for destroys this is strictly required otherwise, the link will produce a POST or a PATCH.

2021-02-12 15:34 UTC, juanhurtado10 commented on app/views/layouts/external.html.erb
> +                                <% cached_categories.sample(15).each do |category| %>
@xleed-dev cool ... you're gonna see this in many projects!

2021-02-16 16:00 UTC, merged