Followers functionality implemented
xleed-dev/Rails-Blog pull request #2
Opened 2021-02-11 22:50 UTC by xleed-dev

- Previous PR recommendations implemented
- Some code clean and refactors
- **Followers functionalities implemented**

2021-02-12 15:48 UTC, juanhurtado10 requested changes
@xleed-dev Outstanding work 🚀. The indentation issues persist and need to be fixed in all the code instances including the templates. Also, blank spaces need to be trimmed, these both things can be managed by your IDE.

2021-02-12 15:48 UTC, juanhurtado10 commented on app/controllers/application_controller.rb
> +        redirect_to '/unauthorized' unless logged_in?
@xleed-dev this needs to be handled by the routes helper methods. We should not use static paths when routing, due to if a route changes all the code instances need to updated as well.

2021-02-12 15:48 UTC, juanhurtado10 commented on app/controllers/application_controller.rb
> +        User.find_by(id: session[:user_id])
@xleed-dev indentation issues persist!

2021-02-12 15:48 UTC, juanhurtado10 commented on app/controllers/articles_controller.rb
> +
@xleed-dev We need to ensure that blank spaces are trimmed!

2021-02-12 15:48 UTC, juanhurtado10 commented on app/controllers/articles_controller.rb
> +    params.require(:article).permit(:title, :body, :status, :image_url, :category_id, :user_id)
@xleed-dev what **require** and **permit** does ?

2021-02-12 15:48 UTC, juanhurtado10 commented on app/controllers/users_controller.rb
> +    followed.followers << follower
@xleed-dev what if for some reason the **followed** instance is nil?

2021-02-12 15:48 UTC, juanhurtado10 commented on app/models/user.rb
> +    has_many :followers, :through => :rel_followers, :source => :follower
@xleed-dev what the ** through** attribute does?

2021-02-12 15:48 UTC, juanhurtado10 commented on app/views/articles/forbiden.html.erb
> +    (<%= link_to '@'+@article.user.username, @article.user %>)
@xleed-dev a helper method will help with `'@'+@article.user.username` a better approach than doing so in the view

2021-02-12 15:48 UTC, juanhurtado10 commented on config/routes.rb
> +  resources :users, only: [:new,:create,:index,:show]
@xleed-dev what the **resources** helper method does?

2021-02-12 15:48 UTC, juanhurtado10 commented on app/controllers/sessions_controller.rb
> +    redirect_to wellcome_path
@xleed-dev Excellent this is what I'm looking for when routing!

2021-02-15 14:35 UTC, xleed-dev commented on app/controllers/articles_controller.rb
> +    params.require(:article).permit(:title, :body, :status, :image_url, :category_id, :user_id)
`require` tells ruby that the `:article` object is mandatory to be included in the request data.
`permit` is used to limit the attributes passed by the request, this is performed to avoid security issues

2021-02-15 14:41 UTC, xleed-dev commented on app/controllers/users_controller.rb
> +    followed.followers << follower
Rails would throw an exception like this:
```ActiveRecord::RecordNotFound (Couldn't find User with 'id'=...)```
But the front end may not show the appropriate message to the user, so I will add some validations so that these types of errors are reported properly on the front-end

2021-02-15 14:59 UTC, xleed-dev commented on app/models/user.rb
> +    has_many :followers, :through => :rel_followers, :source => :follower
Uses an existing declared relation (`:rel_followers` which connects the `users` table with the `follows` one) to set up a many-to-many connection. In this case, I'm using it to associate the `followed_id` column from the `follows` table with the `id` column of the `users` table to access the users that are *following* ***this*** user

2021-02-15 15:06 UTC, xleed-dev commented on config/routes.rb
> +  resources :users, only: [:new,:create,:index,:show]
Creates the appropriate routes with the appropriate method (`GET`, `POST`, `PUT`...) for the specified model (in this case `User`) so we don't have to write them separately. By default, it creates all the common *CRUD* routes so I'm telling it to only create the specified ones with the `only` parameter

2021-02-15 20:52 UTC, juanhurtado10 commented on app/controllers/users_controller.rb
> +  def add_follower
@xleed-dev is this a follow action? am I right? if the answer is yes, let's call it **follow**

2021-02-15 20:52 UTC, juanhurtado10 commented on app/controllers/users_controller.rb
> +  def del_follower
@xleed-dev naming things is hard but it is also an important part when we're writing code. **Unfollow** will be a better fit here ... I guess.

2021-02-15 20:52 UTC, juanhurtado10 commented on app/models/user.rb
> +  def equal?(other)
@xleed-dev what about this abstraction?

```
    return false if other.blank?  
    self.id == other.id
```

2021-02-16 00:22 UTC, xleed-dev commented on app/controllers/articles_controller.rb
> +    unless current_user.followeds.include? @article.user or current_user == @article.user
I thought of creating a *before action filter* but I would need both users (article's author and current user) to be accessible from that method and they aren't constant across all controller's methods. So instead I created the `can_see?` method in the `User` model so I can use that validation here and on comments

2021-02-16 00:22 UTC, xleed-dev commented on app/controllers/users_controller.rb
> +  def add_follower
You are right, I renamed it

2021-02-16 00:22 UTC, xleed-dev commented on app/controllers/users_controller.rb
> +  def del_follower
You are right, I renamed it to *unfollow*

2021-02-16 00:22 UTC, xleed-dev commented on app/models/user.rb
> +  def equal?(other)
Thank you, that's cleaner, I didn't know the `blank?` method

2021-02-16 15:56 UTC, juanhurtado10 commented on app/controllers/articles_controller.rb
> +    unless current_user.followeds.include? @article.user or current_user == @article.user
@xleed-dev good solution! 👏🏻

2021-02-16 15:57 UTC, juanhurtado10 commented on app/models/user.rb
> +  def equal?(other)
@xleed-dev **blank?** checks two conditions: if the object is nil or if it is an empty sting "".

2021-02-16 16:00 UTC, juanhurtado10 approved these changes
@xleed-dev awesome job done! Now you can deploy these changes :)

2021-02-16 16:00 UTC, merged